name: coming_soon
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1   # ← نسخه را به v2 رساندم

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pocketbase: ^0.18.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
